### PR TITLE
Submission for 10/16 Assignment Brendan Egan

### PR DESCRIPTION
**Pull request by HumbleEntLord**

### CODE REVIEW

**Comment by ElizabethBrooks** [comment]
Good work! There was a small typo in part c of #2, where the column being used for filtering was Petal.Length rather than Sepal.Width.

**Comment by HumbleEntLord** [comment]
Thanks so much, Elizabeth!

Quick question about the exercise.  First, is it due tonight or tomorrow?
On the worksheet it says tomorrow, though on Sakai it says this evening.

Secondly, I am a little confused by the phrasing 'generate a script that
simulates the growth of the two sub-pops. in the tumor to equilibrium
followed by drug treatment'.  Does this mean that we need to plot both the
initial equilibrium, and then that reached when drugs are introduced? Or is
this only the graph which would start at equilibrium and follow after the
introduction of a drug?

Thanks so much,
Brendan

**Comment by ElizabethBrooks** [comment]
Hello,

I just saw your comment on GitHub and decided to email you, in addition to replying to the comment on the pull request. The exercise is due tomorrow. Feel free to submit it in the evening tomorrow.

For the phrasing 'generate a script that simulates the growth of the two sub-pops. in the tumor to equilibrium followed by drug treatment', it is referring to just a single plot where you will see a swap in the growth lines at the timestep that the drug is introduced (see example output plot in email). 

Try adding the drug (changing the rate of growth for each pop) at different timesteps to find a time that has the desired effect on the growth of the populations. So, you will just need an if-statement in the simulation for-loop that switches the rate of growth used by each of the functions for the normal and mutant cell populations.

Hope this helps! Let me know if you have any other questions.
-Elizabeth

**Pull request closed without merging**
